### ISSUE TITLE
Add a Gather-Sum-Apply iteration method

### ISSUE THREAD

**Issue by vasia** [project-flink/flink-graph#33]
This will be a method that implements the GAS computation model, as described [here] (http://graphlab.org/files/osdi2012-gonzalez-low-gu-bickson-guestrin.pdf), but without the "scatter" step. The phases can be mapped into the following steps inside a delta iteration: 
- gather: a map on each < srcVertex, edge, trgVertex > that produces a partial value
- sum: a reduce that combines the partial values 
- apply: join with vertex set to update the vertex values using the results of sum and the previous state

We may consider adding also a variation that does not use an iteration, but performs a single-update to the vertex values.

**Comment by balidani** [comment]
Hi!

I started working on this again and I have more questions.
So far, I started implementing a GAS solution to greedy graph coloring using Vasia's outline inside an empty test class. This is what I have right now: https://gist.github.com/balidani/9d1bd23942726da8db5b

I'm stuck after computing `groupedTriplets`, since after that I should join with the vertices, but we lost all reference to the original vertex by that time. Should I propagate <vertexId, Set(trg)> instead of just the Set, or am I missing something that would allow me to still make a join?

I can't really test this code either, because it's inside a delta iteration and it has to be completed with `closeWith` to be executable.

Thanks!

**Comment by vasia** [comment]
Hi @balidani! Great that you resumed working on this :)

It might be a good idea to write an example without the iteration and then move your dataflow inside one. 
Let's assume that you only need to make one gather-apply-sum pass for the graph coloring.

First of all, your `mappedTriplets` dataset should also preserve the source vertex. Otherwise, what are you going to group by in the sum phase?

Then, your `groupedTriplets` dataset also needs to preserve the source vertex and will look like this:
`DataSet<Vertex<Long, Long>, HashSet<Vertex<Long, Long>>> groupedTriplets = ...`

After you have computed the `groupedTriplets`, you can join with the initial graph vertex dataset and update the vertex values. Finally, put this dataflow inside a delta iteration. 

What we need for the graph api is a method that will wrap this dataflow, so that the triplets creation, the iteration, the grouping and the join are hidden from the user. Makes sense?

**Comment by balidani** [comment]
Yeah, thanks for the clarification, this is what I meant by propagating the source vertex id.
I'll test without the iteration and see what happens :)

**Comment by balidani** [comment]
Hi!

I implemented one iteration without actually using delta iterations and the result was as expected.
Then I tried to use delta iterations. For `closeWith` I simply used the `newVertices` values, expecting the iteration to terminate after `maxIterations` (16 in this case), but only one iteration is performed.

Here is my commit: https://github.com/balidani/flink-graph/commit/471dff804e47b250ed252f7f950d7457b4cde63f

What am I doing wrong?

**Comment by vasia** [comment]
Hi @balidani! I tried out your code and I see 16 iterations being executed.. However, with the data that you're using and a delta iteration, the program only needs 2 iterations to terminate.
This is because, you only need to emit the updated elements in the workset, but you emit everything.
I will add some inline comments!

**Comment by balidani** [comment]
Hi @vasia!

I made the changes (https://github.com/balidani/flink-graph/commit/4d8d762c57feba6a7ee17661eab8cf6a328495b1), but it still does not work. I don't understand why and it seems hard to debug, since printing any intermediate DataSet will cause an exception. I thought I finally understood delta iterations, but no :) Sorry for all the confusion.

**Comment by vasia** [comment]
What's the problem now? It seems like working to me :octopus:

**Comment by balidani** [comment]
Well, the output is still
```
(1,1)
(2,2)
(3,3)
(4,4)
(5,1)
```

After vertex 5 becomes (5, 1), vertex 4 and 3 are supposed to take that value as well, but they don't.

**Comment by vasia** [comment]
Right, this must be because of the way you're creating the triplets.
You join the graph edges with the vertices to create the `<edge, trg>` and then join with the workset to create the `<src, edge, trg>` triplet.
This has two problems: (1) your trg vertices will carry the old values (you don't update the graph inside the iteration!) and (2) you will only get the sources which existed in the previous workset.
What you want is the fresh `trg` values for all the `src` vertices, i.e. you need to take the target from the iteration workset and the sources from the iteration solution set.

**Comment by vasia** [comment]
Moved to [FLINK-1514](https://issues.apache.org/jira/browse/FLINK-1514).
